language: java
before_script:
  - wget http://156.35.82.101:7000/downloads/acota/utils/travis/core/acota.properties
  - mv acota.properties acota-core/acota.properties
  - wget http://156.35.82.101:7000/downloads/acota/utils/SpanishPOS.bin
  - wget http://156.35.82.101:7000/downloads/acota/utils/SpanishSent.bin
  - wget http://wordnetcode.princeton.edu/3.0/WNdb-3.0.tar.gz
  - tar -xzf WNdb-3.0.tar.gz
script: mvn -f acota-core/pom.xml install test
jdk:
  - openjdk6
notifications:
  email:
    - sisa989@gmail.com
